import pentominos
import copy

# p = pentominos.Y()
# print p.representation()
# print p.__hash__()
# p2 = copy.deepcopy(p)
# p2.flip(0)
# print p2.representation()
# print p2.__hash__()
# print p.__eq__(p2)
# p.flip(1)
# print p.representation()
# print p.__hash__()
# p.flip(0)
# print p.representation()
# print p.__hash__()


# X = pentominos.TileSet()
# p = pentominos.I()
# X.add(copy.deepcopy(p))
# p.flip(0)
# #p.turn90()
# X.add(copy.deepcopy(p))
# print X.representation()

reps = pentominos.TileSet()
p = pentominos.Y()
print reps.representation()
reps.add(p)
print reps.representation()
p.flip(0)
print reps.representation()
reps.add(p)
print reps.representation()
p.flip(1)
reps.add(p)
p.flip(0)
reps.add(p)