SHELL = /bin/sh

.SUFFIXES:
.SUFFIXES: .cc .o

BOOSTDIR = /the/path/to/your/boost # was: /home/julian/software/boost_1_57_0

INCLUDEDIR = -I. -I$(BOOSTDIR)
LIBDIR = -L$(BOOSTDIR)/lib
LIBS = -lboost_unit_test_framework
CFLAGS = -Wall -Wextra -Wpedantic -std=c++1y -O3 -g
CC = g++

test_orbits: test_orbits.o
	$(CC) $(LIBDIR) $(CFLAGS) $< $(LIBS) -o $@

test_orbits.o: test_orbits.cc orbit.h
	$(CC) $(INCLUDEDIR) $(CFLAGS) -c $< -o $@
